# Generated by Django 6.0.4 on 2026-04-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationsettings',
            name='login_href',
            field=models.CharField(default='#login', max_length=255),
        ),
        migrations.AddField(
            model_name='navigationsettings',
            name='login_label',
            field=models.CharField(default='Login', max_length=100),
        ),
        migrations.AlterField(
            model_name='navigationsettings',
            name='cta_label',
            field=models.CharField(default='Book a Demo', max_length=100),
        ),
    ]
