# Generated by Django 6.0.4 on 2026-05-04 14:02

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_carepage_body'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifestylePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('lifestyle_hero', 14), ('cta_banner', 18), ('testimonials', 26), ('faq_accordion', 32), ('newsletter', 35)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Wellness for Every Stage of Life', 'max_length': 100, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'Holistic Wellness,\nAccessible Anytime,\nAnywhere', 'max_length': 300, 'required': False}), 2: ('wagtail.blocks.TextBlock', (), {'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Upload the hero image (leave empty to show placeholder)', 'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('top', 'Top (above image)'), ('right', 'Right (mid-right)'), ('bottom', 'Bottom-left')], 'help_text': 'Visual position of this card over the hero image', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. Six Wellness Disciplines', 'max_length': 100, 'required': False}), 6: ('wagtail.blocks.TextBlock', (), {'help_text': 'Short description shown in italic below the heading', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('position', 4), ('heading', 5), ('text', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {'label': 'Floating Info Cards (max 3)', 'max_num': 3, 'min_num': 0}), 9: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'default': '#', 'max_length': 255, 'required': False}), 11: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary (dark navy fill)'), ('outline', 'Outline (white border)'), ('outline-white', 'Outline White (thick white border)'), ('accent', 'Accent (orange/red fill)'), ('green', 'Green (lifestyle fill)'), ('text-arrow', 'Text Arrow (borderless)')]}), 12: ('wagtail.blocks.StructBlock', [[('label', 9), ('href', 10), ('style', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'label': 'CTA Buttons', 'min_num': 0}), 14: ('wagtail.blocks.StructBlock', [[('tag', 0), ('heading', 1), ('body', 2), ('image', 3), ('info_cards', 8), ('ctas', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 16: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Video thumbnail / side image', 'required': False}), 17: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('white', 'White'), ('off-white', 'Off-White'), ('dark', 'Dark Navy')], 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('heading', 15), ('subtitle', 2), ('image', 16), ('background', 17), ('ctas', 13)]], {}), 19: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': False}), 20: ('wagtail.blocks.IntegerBlock', (), {'default': 5, 'max_value': 5, 'min_value': 1}), 21: ('wagtail.blocks.TextBlock', (), {}), 22: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 23: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 24: ('wagtail.blocks.StructBlock', [[('stars', 20), ('text', 21), ('author', 22), ('role', 9), ('image', 23)]], {}), 25: ('wagtail.blocks.ListBlock', (24,), {}), 26: ('wagtail.blocks.StructBlock', [[('tag', 19), ('heading', 15), ('background', 17), ('items', 25)]], {}), 27: ('wagtail.blocks.CharBlock', (), {'max_length': 300, 'required': False}), 28: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 29: ('wagtail.blocks.StructBlock', [[('question', 27), ('answer', 2), ('default_open', 28)]], {}), 30: ('wagtail.blocks.ListBlock', (29,), {'label': 'FAQ Items', 'min_num': 0}), 31: ('wagtail.blocks.StructBlock', [[('label', 9), ('href', 10), ('style', 11)]], {'required': False}), 32: ('wagtail.blocks.StructBlock', [[('tag', 19), ('heading', 15), ('subtitle', 2), ('background', 17), ('items', 30), ('footer_heading', 15), ('footer_body', 2), ('footer_cta', 31)]], {}), 33: ('wagtail.blocks.CharBlock', (), {'default': 'Enter your email address', 'max_length': 100, 'required': False}), 34: ('wagtail.blocks.CharBlock', (), {'default': 'Sign Up Free', 'max_length': 50, 'required': False}), 35: ('wagtail.blocks.StructBlock', [[('heading', 27), ('subtitle', 2), ('input_placeholder', 33), ('submit_label', 34), ('background', 17), ('disclaimer', 2)]], {})})),
            ],
            options={
                'verbose_name': 'Lifestyle Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
